### ISSUE TITLE
Inclination of the graph

### ISSUE THREAD

**Issue by syldor** [kjhealy/lexis_surface#1]
Thank you for your code and a great visualization.
In the [blog post](https://kieranhealy.org/blog/archives/2018/12/04/heatmaps-of-mortality-rates/), the graph shows up as having a rectangle shape
![selection_500](https://user-images.githubusercontent.com/4158062/50671400-3f559e00-1004-11e9-955c-e6315783592b.png)

when in this code it's more of a diamond shape.

![britain_men](https://user-images.githubusercontent.com/4158062/50671385-2baa3780-1004-11e9-8ab2-43992c7cf71b.png)

How is the correction made and what does it mean?

I feel like I'm not grasping what is actually plotted.

**Comment by kjhealy** [comment]
I can't reproduce this. Assuming you have the right data from mortality.org, and it's loaded as at the top of `lexis.r`, this code:

```p <- ggplot(subset(britain, age < 101), aes(x = year, y = age, fill = ntile(male, 100)))
p_out <- p + geom_raster() +
    scale_fill_viridis_c(option = "A", direction = -1) +
    scale_x_continuous(breaks = seq(1845, 2015, by = 15)) +
    ylim(c(0, 100)) +
    guides(fill = guide_legend(nrow = 1, title.position = "top", label.position = "bottom")) +
    labs(x = "Year", y = "Age", fill = "Male Death Rate Percentile",
         title = "Male Mortality Rates in England and Wales, 1841-2016",
         subtitle = "Binned by percentile",
         caption = "@kjhealy / http://socviz.co. Data: Human Mortality Database.") +
    theme(legend.position = "top",
          legend.title = element_text(size = 8))

p_out
```

Should give you this figure: 

<img width="726" alt="screen shot 2019-01-04 at 7 40 07 am" src="https://user-images.githubusercontent.com/5760/50688559-f695e900-0ff3-11e9-84b3-d58db33e0b61.png">

**Comment by syldor** [comment]
Damn, I was plotting the cohort mortality rate instead of the periodic one. Thank you for your answer :)

**Comment by syldor** [comment]
I have another question. What do you mean by 

> If you plot the raw mortality rates, what you’ll find is that the wars tend to drown out all the other data in the series, washing out the other trends.

I understand that when we plot the raw mortality rates we only see two patterns appearing:

- Older people have higher mortality rates
- During the wars, 19-45yo people have higher mortality rates

![selection_501](https://user-images.githubusercontent.com/4158062/50719139-8c03ac80-10ca-11e9-82dc-2f6f27689b70.png)

And I understand that because we cannot see the other trends from your article you decided to take a different "lens" by doing the binning, **but why are the war responsible for that?**

(I'm really just asking because I find the article amazing and try to fully grasp it and not because I'm looking for issues :))
